version: "2"
services:
  metaaldetectievondstmeldingen-urireferencer:
    image: metaaldetectievondstmeldingen-dev/uriregistry:latest
    ports:
      - "6542:6543"
  metaaldetectievondstmeldingen-rqworker:
    image: metaaldetectievondstmeldingen-dev/metaaldetectievondstmeldingen:latest
    links:
     - metaaldetectievondstmeldingen-elastic:elastic
     - metaaldetectievondstmeldingen-db:postgres
     - metaaldetectievondstmeldingen-storage-provider:storageprovider
     - metaaldetectievondstmeldingen-redis:redis
    command: rqworker -u "http://redis:6379" metaaldetectievondstmeldingen_backend_jobs
  metaaldetectievondstmeldingen-elastic:
    image: geosolutions/elasticsearch-plugins
    ports:
      - "9200:9200"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
  metaaldetectievondstmeldingen-db:
    image: metaaldetectievondstmeldingen-dev/postgres:latest
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  metaaldetectievondstmeldingen-storage-provider:
    image: metaaldetectievondstmeldingen-dev/storageprovider:latest
    ports:
      - "6544:6544"
    volumes:
      - ./data/storageprovider:/metaaldetectievondstmeldingen_store
  metaaldetectievondstmeldingen-redis:
    image: redis
    ports:
      - "6379:6379"
  metaaldetectievondstmeldingen-app:
    image: metaaldetectievondstmeldingen-dev/metaaldetectievondstmeldingen:latest
    ports:
     - "6543:6543"
    volumes:
     - ./metaaldetectievondstmeldingen/metaaldetectievondstmeldingen:/app/metaaldetectievondstmeldingen
     - ./metaaldetectievondstmeldingen/alembic:/app/alembic
     - ./metaaldetectievondstmeldingen/deploy:/app/deploy
     - ./metaaldetectievondstmeldingen/tests:/app/tests
     - ./metaaldetectievondstmeldingen/docs:/app/docs
     - ./metaaldetectievondstmeldingen/alembic.ini:/app/alembic.ini
     - ./metaaldetectievondstmeldingen/production.ini:/app/production.ini
    links:
     - metaaldetectievondstmeldingen-db:postgres
     - metaaldetectievondstmeldingen-redis:redis
     - metaaldetectievondstmeldingen-storage-provider:storageprovider
     - metaaldetectievondstmeldingen-elastic:elastic
     - metaaldetectievondstmeldingen-urireferencer:urireferencer

