version: "2"
services:
  metaaldetectievondstmeldingen-db:
    image: metaaldetectievondstmeldingen-dev/postgres:latest
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  metaaldetectievondstmeldingen-redis:
    image: redis
    ports:
      - "6379:6379"
  metaaldetectievondstmeldingen-app:
    image: metaaldetectievondstmeldingen-dev/metaaldetectievondstmeldingen:latest
    ports:
     - "6543:6543"
    volumes:
     - ./metaaldetectievondstmeldingen/metaaldetectievondstmeldingen:/app/metaaldetectievondstmeldingen
     - ./metaaldetectievondstmeldingen/alembic:/app/alembic
     - ./metaaldetectievondstmeldingen/deploy:/app/deploy
     - ./metaaldetectievondstmeldingen/tests:/app/tests
     - ./metaaldetectievondstmeldingen/docs:/app/docs
     - ./metaaldetectievondstmeldingen/alembic.ini:/app/alembic.ini
     - ./metaaldetectievondstmeldingen/production.ini:/app/production.ini
    links:
     - metaaldetectievondstmeldingen-db:postgres
     - metaaldetectievondstmeldingen-redis:redis

