version: "2"
services:
  metaaldetectievondsten-db:
    image: metaaldetectievondsten-dev/postgres:latest
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  metaaldetectievondsten-elastic:
#    image: geosolutions/elasticsearch-plugins
#    ports:
#      - "9200:9200"
#    volumes:
#      - ./data/elastic:/usr/share/elasticsearch/data
  metaaldetectievondsten-redis:
    image: redis
    ports:
      - "6379:6379"
#  metaaldetectievondsten-storage-provider:
#    image: metaaldetectievondsten-dev/storageprovider:latest
#    ports:
#     - "6544:6544"
#    volumes:
#     - ./data/storageprovider:/metaaldetectievondsten_store
#  metaaldetectievondsten-rqworker:
#    image: metaaldetectievondsten-dev/metaaldetectievondsten:latest
#    links:
#     - metaaldetectievondsten-elastic:elastic
#     - metaaldetectievondsten-db:postgres
#     - metaaldetectievondsten-storage-provider:storageprovider
#     - metaaldetectievondsten-redis:redis
#    command: rqworker --host redis metaaldetectievondsten_es_indexer
  metaaldetectievondsten-app:
    image: metaaldetectievondsten-dev/metaaldetectievondsten:latest
    ports:
     - "6543:6543"
    volumes:
     - ./metaaldetectievondsten/metaaldetectievondsten:/app/metaaldetectievondsten
     - ./metaaldetectievondsten/alembic:/app/alembic
     - ./metaaldetectievondsten/deploy:/app/deploy
     - ./metaaldetectievondsten/tests:/app/tests
     - ./metaaldetectievondsten/docs:/app/docs
     - ./metaaldetectievondsten/alembic.ini:/app/alembic.ini
     - ./metaaldetectievondsten/production.ini:/app/production.ini
     - ./metaaldetectievondsten/development.ini:/app/development.ini
    links:
#     - metaaldetectievondsten-elastic:elastic
     - metaaldetectievondsten-db:postgres
#     - metaaldetectievondsten-storage-provider:storageprovider
     - metaaldetectievondsten-redis:redis

