FROM metaaldetectievondstmeldingen-dev/metaaldetectievondstmeldingen:latest

WORKDIR "/app"
CMD ["sh", "-c", "initialize_metaaldetectievondstmeldingen_db development.ini#metaaldetectievondstmeldingen; initialize_metaaldetectievondstmeldingen_es development.ini#metaaldetectievondstmeldingen"]
